#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
import sys

TOOLS_DIR = Path(__file__).resolve().parents[1]
if str(TOOLS_DIR) not in sys.path:
    sys.path.append(str(TOOLS_DIR))

from common.pathing import axion_path


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_json(path: Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except Exception:
        return default


def to_path(raw: str | None, fallback_parts: tuple[str, ...]) -> Path:
    text = str(raw or "").strip()
    if not text:
        return axion_path(*fallback_parts)
    p = Path(text)
    if p.is_absolute():
        return p
    return axion_path(*Path(text).parts)


def mask_from_classes(classes: list[int]) -> int:
    mask = 0
    for cls in classes:
        if isinstance(cls, int) and 0 <= cls <= 63:
            mask |= (1 << cls)
    return mask


def read_policy(path: Path) -> dict:
    policy = load_json(path, {})
    if not isinstance(policy, dict):
        return {}
    return policy


def render_header(payload: dict) -> str:
    return (
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "// Auto-generated by tools/kernel/generate_parallel_cubed_hardware_guard.py\n"
        "#define AX_PCGUARD_ENABLED ((uint64_t){enabled}u)\n"
        "#define AX_PCGUARD_STRICT_MODE ((uint64_t){strict_mode}u)\n"
        "#define AX_PCGUARD_INVENTORY_REQUIRED ((uint64_t){inventory_required}u)\n"
        "#define AX_PCGUARD_ALLOW_MASK ((uint64_t)0x{allow_mask:016x}ull)\n"
        "#define AX_PCGUARD_DENY_MASK ((uint64_t)0x{deny_mask:016x}ull)\n"
    ).format(**payload)


def generate_parallel_cubed_hardware_guard(
    *,
    policy_path: str | Path | None = None,
    header_path: str | Path | None = None,
    out_path: str | Path | None = None,
) -> dict:
    policy_file = to_path(str(policy_path) if policy_path is not None else "", ("config", "PARALLEL_CUBED_HARDWARE_GUARD_V1.json"))
    header_file = to_path(str(header_path) if header_path is not None else "", ("kernel", "include", "axion", "runtime", "parallel_cubed_hardware_guard.h"))
    out_file = to_path(str(out_path) if out_path is not None else "", ("out", "runtime", "parallel_cubed_hardware_guard.json"))

    policy = read_policy(policy_file)

    allow_classes = [int(x) for x in (policy.get("allowBusClasses") or []) if isinstance(x, int) or str(x).isdigit()]
    deny_classes = [int(x) for x in (policy.get("denyBusClasses") or []) if isinstance(x, int) or str(x).isdigit()]

    payload = {
        "enabled": 1 if bool(policy.get("enabled", True)) else 0,
        "strict_mode": 1 if bool(policy.get("strictMode", True)) else 0,
        "inventory_required": 1 if bool(policy.get("inventoryRequiredBeforeSmartWrite", True)) else 0,
        "allow_mask": mask_from_classes(allow_classes),
        "deny_mask": mask_from_classes(deny_classes),
        "allow_bus_classes": allow_classes,
        "deny_bus_classes": deny_classes,
    }

    header_text = render_header(payload)
    header_file.parent.mkdir(parents=True, exist_ok=True)
    header_file.write_text(header_text, encoding="utf-8")

    report = {
        "ok": True,
        "code": "PARALLEL_CUBED_HARDWARE_GUARD_READY",
        "generated_utc": now_iso(),
        "policy_path": str(policy_file),
        "header_path": str(header_file),
        "payload": payload,
    }
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    report["out_path"] = str(out_file)
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--policy-path", default="")
    parser.add_argument("--header-path", default="")
    parser.add_argument("--out-path", default="")
    args = parser.parse_args()

    result = generate_parallel_cubed_hardware_guard(
        policy_path=args.policy_path or None,
        header_path=args.header_path or None,
        out_path=args.out_path or None,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
