#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
import sys

TOOLS_DIR = Path(__file__).resolve().parents[1]
if str(TOOLS_DIR) not in sys.path:
    sys.path.append(str(TOOLS_DIR))

from common.pathing import axion_path


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_json(path: Path, default):
    if not path.exists():
        return default
    try:
        value = json.loads(path.read_text(encoding="utf-8-sig"))
    except Exception:
        return default
    return value


def _to_path(raw: str | None, fallback_parts: tuple[str, ...]) -> Path:
    text = str(raw or "").strip()
    if not text:
        return axion_path(*fallback_parts)
    p = Path(text)
    if p.is_absolute():
        return p
    return axion_path(*Path(text).parts)


def _read_smart_driver_config() -> dict:
    cfg_path = axion_path("config", "SMART_DRIVER_FABRIC_V1.json")
    cfg = _load_json(cfg_path, {})
    return cfg if isinstance(cfg, dict) else {}


def _token_split(token: str) -> tuple[int, int]:
    text = str(token or "").strip().lower()
    if len(text) < 32:
        return (0, 0)
    try:
        hi = int(text[:16], 16)
        lo = int(text[16:32], 16)
    except Exception:
        return (0, 0)
    return (hi, lo)


def _header_payload(state: dict, registry: dict) -> dict:
    load_once_token = str(state.get("load_once_token", "")).strip()
    token_hi, token_lo = _token_split(load_once_token)
    resolved_total = len([x for x in state.get("resolved_driver_ids", []) if str(x).strip()])
    synthesized_total = len([x for x in state.get("synthesized_drivers", []) if isinstance(x, dict)])
    artifacts = [x for x in registry.get("artifacts", []) if isinstance(x, dict)] if isinstance(registry, dict) else []
    signed_artifacts_total = len(
        [x for x in artifacts if str(x.get("status", "")).strip().lower() == "compiled_signed_verified"]
    )
    return {
        "ready": 1 if bool(state.get("ready")) else 0,
        "load_once_token": load_once_token,
        "token_hi": token_hi,
        "token_lo": token_lo,
        "target_bsp_id": str(state.get("target_bsp_id", "")).strip() or "unknown",
        "target_family": str(state.get("target_family", "")).strip() or "unknown",
        "resolved_total": resolved_total,
        "synthesized_total": synthesized_total,
        "signed_artifacts_total": signed_artifacts_total,
    }


def _render_header(payload: dict) -> str:
    return (
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "// Auto-generated by tools/kernel/generate_smart_driver_handoff.py\n"
        "#define AX_SDF_HANDOFF_READY ((uint64_t){ready}u)\n"
        "#define AX_SDF_HANDOFF_LOAD_ONCE_TOKEN_HI ((uint64_t)0x{token_hi:016x}ull)\n"
        "#define AX_SDF_HANDOFF_LOAD_ONCE_TOKEN_LO ((uint64_t)0x{token_lo:016x}ull)\n"
        "#define AX_SDF_HANDOFF_RESOLVED_TOTAL ((uint64_t){resolved_total}u)\n"
        "#define AX_SDF_HANDOFF_SYNTHESIZED_TOTAL ((uint64_t){synthesized_total}u)\n"
        "#define AX_SDF_HANDOFF_SIGNED_ARTIFACTS_TOTAL ((uint64_t){signed_artifacts_total}u)\n\n"
    ).format(**payload)


def generate_smart_driver_handoff(
    *,
    state_path: str | Path | None = None,
    artifact_registry_path: str | Path | None = None,
    header_path: str | Path | None = None,
    out_path: str | Path | None = None,
) -> dict:
    cfg = _read_smart_driver_config()
    state_default = str(cfg.get("state_path") or "")
    registry_default = str(cfg.get("artifact_registry_path") or "")

    state_file = _to_path(str(state_path) if state_path is not None else state_default, ("data", "drivers", "smart_driver_fabric_state.json"))
    registry_file = _to_path(
        str(artifact_registry_path) if artifact_registry_path is not None else registry_default,
        ("data", "drivers", "smart_driver_fabric_artifact_registry.json"),
    )
    header_file = _to_path(str(header_path) if header_path is not None else "", ("kernel", "include", "axion", "runtime", "smart_driver_handoff.h"))
    out_file = _to_path(str(out_path) if out_path is not None else "", ("out", "runtime", "smart_driver_kernel_handoff.json"))

    state = _load_json(state_file, {})
    registry = _load_json(registry_file, {})
    if not isinstance(state, dict):
        state = {}
    if not isinstance(registry, dict):
        registry = {}

    payload = _header_payload(state, registry)
    header_text = _render_header(payload)
    header_file.parent.mkdir(parents=True, exist_ok=True)
    header_file.write_text(header_text, encoding="utf-8")

    report = {
        "ok": True,
        "code": "SMART_DRIVER_KERNEL_HANDOFF_READY",
        "generated_utc": _now_iso(),
        "state_path": str(state_file),
        "artifact_registry_path": str(registry_file),
        "header_path": str(header_file),
        "payload": payload,
    }
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    report["out_path"] = str(out_file)
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--state-path", default="")
    parser.add_argument("--artifact-registry-path", default="")
    parser.add_argument("--header-path", default="")
    parser.add_argument("--out-path", default="")
    args = parser.parse_args()
    result = generate_smart_driver_handoff(
        state_path=args.state_path or None,
        artifact_registry_path=args.artifact_registry_path or None,
        header_path=args.header_path or None,
        out_path=args.out_path or None,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
