DECISION_PROMOTE_OK = 'PROMOTE_OK'
DECISION_REJECT_SCHEMA = 'REJECT_SCHEMA'
DECISION_REJECT_HASH = 'REJECT_HASH'
DECISION_REJECT_POLICY = 'REJECT_POLICY'
DECISION_REJECT_SCAN = 'REJECT_SCAN'
DECISION_REJECT_IG = 'REJECT_IG'

EXIT_OK = 0
EXIT_SCHEMA = 10
EXIT_HASH = 11
EXIT_POLICY = 12
EXIT_SCAN = 13
EXIT_IG = 14
EXIT_INTERNAL = 20
