#pragma once
#include <stdint.h>

// Auto-generated by tools/kernel/generate_parallel_cubed_hardware_guard.py
#define AX_PCGUARD_ENABLED ((uint64_t)1u)
#define AX_PCGUARD_STRICT_MODE ((uint64_t)1u)
#define AX_PCGUARD_INVENTORY_REQUIRED ((uint64_t)1u)
#define AX_PCGUARD_ALLOW_MASK ((uint64_t)0x0000000000000046ull)
#define AX_PCGUARD_DENY_MASK ((uint64_t)0x0000000000003000ull)
