#pragma once
#include <stdint.h>

// Auto-generated by tools/kernel/generate_smart_driver_handoff.py
#define AX_SDF_HANDOFF_READY ((uint64_t)1u)
#define AX_SDF_HANDOFF_LOAD_ONCE_TOKEN_HI ((uint64_t)0xde159242110bec05ull)
#define AX_SDF_HANDOFF_LOAD_ONCE_TOKEN_LO ((uint64_t)0x6b7ba299be19c4f4ull)
#define AX_SDF_HANDOFF_RESOLVED_TOTAL ((uint64_t)8u)
#define AX_SDF_HANDOFF_SYNTHESIZED_TOTAL ((uint64_t)2u)
#define AX_SDF_HANDOFF_SIGNED_ARTIFACTS_TOTAL ((uint64_t)2u)

